### ISSUE TITLE
Bug: results_aggregation.py list index out of range

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#12]
When executing the command

`python3 results_aggregation.py test-result output.html --regression 'OEM Query Catalog'`

using the rest results

https://sap.sharepoint.com/:f:/r/teams/SAPDataspaceConnector/Shared%20Documents/General/Performance%20Meassurements%20Tx-Edc/[20240409](https://sap.sharepoint.com/:f:/r/teams/SAPDataspaceConnector/Shared%20Documents/General/Performance%20Meassurements%20Tx-Edc/20240409?csf=1&web=1&e=gBxvgO)?csf=1&web=1&e=gBxvgO

the following error is reported:

Traceback (most recent call last):
  File "/Users/xxx/Documents/workspaces/sap-contributions/eclipse-tractusx_tutorial-resources/mxd/performance-tests/mxd-performance-evaluation/results_aggregation.py", line 222, in <module>
    main(directory, html_file, operation_name)
  File "/Users/xxx/Documents/workspaces/sap-contributions/eclipse-tractusx_tutorial-resources/mxd/performance-tests/mxd-performance-evaluation/results_aggregation.py", line 195, in main
    process_folders(root_folder, output_file, operation_name)
  File "/Users/xxx/Documents/workspaces/sap-contributions/eclipse-tractusx_tutorial-resources/mxd/performance-tests/mxd-performance-evaluation/results_aggregation.py", line 190, in process_folders
    plot_process_data(sorted_scenarios, stats_data, output_file)
  File "/Users/xxx/Documents/workspaces/sap-contributions/eclipse-tractusx_tutorial-resources/mxd/performance-tests/mxd-performance-evaluation/results_aggregation.py", line 75, in plot_process_data
    all_calls = stats_data[scenarios[0]].keys()
                           ~~~~~~~~~^^^
IndexError: list index out of range

**Comment by alexandrudanciu** [comment]
@ieuna the root cause is that my experiment result folders don't contain an intermediary output folder. I use to rename the output folder with a meaningful experiment label. I would suggest to change the script and the README so that no intermediary output folder is expected.

**Comment by alexandrudanciu** [comment]
Fixed
