### ISSUE TITLE
MXD 1.0 Develop Backend App

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#25]
- [x] Transfer task from Ravinder to Euna
- [x] Fix Docker image build issue
- [x] Upgrade EDC version

**Comment by ieuna** [comment]
After updating edc version to "v0.6.0" and rewriting related code, getting following error while deploying the pod. The error is coming from edc-boot-system.

```SEVERE 2024-04-22T07:57:39.639644536 Error booting runtime: Provider methods can only have 0..1 arguments, and only accept a ServiceExtensionContext!
java.lang.IllegalArgumentException: Provider methods can only have 0..1 arguments, and only accept a ServiceExtensionContext!
        at org.eclipse.edc.spi.system.injection.ProviderMethod.invoke(ProviderMethod.java:63)
        at org.eclipse.edc.boot.system.injection.lifecycle.RegistrationPhase.invokeAndRegister(RegistrationPhase.java:51)
        at org.eclipse.edc.boot.system.injection.lifecycle.RegistrationPhase.lambda$invokeProviderMethods$0(RegistrationPhase.java:45)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at org.eclipse.edc.boot.system.injection.lifecycle.RegistrationPhase.invokeProviderMethods(RegistrationPhase.java:45)
        at org.eclipse.edc.boot.system.injection.lifecycle.ExtensionLifecycleManager.provide(ExtensionLifecycleManager.java:70)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.eclipse.edc.boot.system.ExtensionLoader.bootServiceExtensions(ExtensionLoader.java:67)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.bootExtensions(BaseRuntime.java:139)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:200)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:83)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:71)
```

**Comment by ieuna** [comment]
Closed with PR: https://github.com/eclipse-tractusx/tutorial-resources/pull/172
